### ISSUE TITLE
Error verifying share

### ISSUE THREAD

**Issue by BitterLox** [blockcypher/libgrin#2] opened 2019-04-01 11:17 UTC
I'm trying to use this library to verify miner shares, but it's logging the error "endpoints don't match"

This is my application log:

Receive work from miner:
```
In: {"id":"0","jsonrpc":"2.0","method":"submit","params":{"edge_bits":29,"height":100455,"job_id":6,"nonce":16079481998891884557,"pow":[4950556,10444042,26994871,63816933,64006601,70454862,74408437,101859857,103156578,103619764,110918645,112676394,156469828,164995210,177571941,197003830,206258400,232973126,235492427,243875402,250871506,261431148,294643091,315606197,320713204,328097841,331983190,340029134,341429798,349593608,352254617,363452582,376534642,385998553,399426703,399588750,417560407,418344217,464144305,478639713,500541067,511159362]}}
```

Convert prepow to byte slice (to use with [VerifyShare](https://github.com/blockcypher/libgrin/blob/master/core/pow.go#L21))
```
DEBU[Apr  1 13:03:56.232566739] JobId 6
DEBU[Apr  1 13:03:56.232672438] prepow:  00010000000000018867000000005ca1f0170b36068977d5b53e8cc9b9d84441a55d375a3462511bb9ecc9d204db5c83f61675a3d19e6b459e6f2152f080fa72d1b2a08046c976a46a89c712b7fbccd0eefed6eb43dd1a16aff97c41c31714a98c2dbb8cc147064a433995f1fd4c0cd5503515ce25e2ff385bfcf930e0a9be63f6c3d9aa03446d3367a1f5f1b7ac3a3be5c12bbd38b081adde256c51b97bf9c8df613fcd4829d4359be0041b968f122da01b9d801ef2914abdaf7a2892571e78fe92e59625018ea6b9aa1bb019a
DEBU[Apr  1 13:03:56.232751983] Prepow []byte: [0 1 0 0 0 0 0 1 136 103 0 0 0 0 92 161 240 23 11 54 6 137 119 213 181 62 140 201 185 216 68 65 165 93 55 90 52 98 81 27 185 236 201 210 4 219 92 131 246 22 117 163 209 158 107 69 158 111 33 82 240 128 250 114 209 178 160 128 70 201 118 164 106 137 199 18 183 251 204 208 238 254 214 235 67 221 26 22 175 249 124 65 195 23 20 169 140 45 187 140 193 71 6 74 67 57 149 241 253 76 12 213 80 53 21 206 37 226 255 56 91 252 249 48 224 169 190 99 246 195 217 170 3 68 109 51 103 161 245 241 183 172 58 59 229 193 43 189 56 176 129 173 222 37 108 81 185 123 249 200 223 97 63 205 72 41 212 53 155 224 4 27 150 143 18 45 160 27 157 128 30 242 145 74 189 175 122 40 146 87 30 120 254 146 229 150 37 1 142 166 185 170 27 176 25 174 122 85 159 58 0 0 0 0 0 4 222 130 0 0 0 0 0 3 211 103 0 0 0 3 208 114 212 188 0 0 0 13]
```
Verifyshare fails:
```
ERRO[Apr  1 13:03:56.233148512] Error processing share: endpoints don't match up
DEBU[Apr  1 13:03:56.233174480] VerifyShare: false
```
Proxy connection to grin stratum server returns blockfound, so the share was valid.
```
DEBU[Apr  1 13:03:56.279445356] Share: {Result:blockfound - 087e45d5f0405e1ada29456ed7050bab592f1e9ed82729f6b41aede39a113dab Err:{Code:0 Msg:}}
```

Code:
```
type SubmitParams struct {
	Height   uint64   `json:"height"`
	JobId    int      `json:"job_id"`
	Nonce    uint64   `json:"nonce"`
	EdgeBits uint8    `json:"edge_bits"`
	Pow      []uint64 `json:"pow"`
}

func VerifyShare(prePoW []uint8, params *SubmitParams) bool {

	header := &hasher.BlockHeader{}
	header.Height = params.Height
	header.PoW.Proof.EdgeBits = params.EdgeBits
	header.PoW.Proof.Nonces = params.Pow

	err := hasher.VerifySize(hasher.Floonet, prePoW, header)

	if err != nil {
		log.Errorf("Error processing share: %v", err)
		return false
	}
	return true
}
```

**Comment by quentinlesceller** [comment] 2019-04-01 11:58
Hi @BitterLox, thanks for the issue this is extremely helpful. We noticed something similar and I was in the process of collecting data. I'll investigate it.

**Comment by quentinlesceller** [comment] 2019-04-01 14:54
Hi @BitterLox after some investigations this is not a bug. Please take a look at https://github.com/blockcypher/libgrin/pull/3. Which is basically your test.
What is missing in your code is that you need to add the nonce at the end of the PrePow. PrePoW length is 238 without nonce and 246 with.
The best way to do this properly would be to code a `PrePoWToBlockHeader` function and then implementing a `prePoW` function for `BlockHeader` just like Grin do.
For posterity here is the rust code for the `PrePoWToBlockHeader` function which we would nee to adapt to Golang (courtesy of @jaspervdm):
```rust
fn block_header(
	pre_pow: Vec<u8>,
	edge_bits: u8,
	nonce: u64,
	proof: Vec<u64>,
) -> Result<BlockHeader, ser::Error> {
	let mut header_bytes = pre_pow;
	let mut nonce_bytes = ser::ser_vec(&nonce)?;
	println!("{:?}", nonce_bytes);
	header_bytes.append(&mut nonce_bytes);
	let mut proof = Proof::new(proof);
	proof.edge_bits = edge_bits;
	let mut proof_bytes = ser::ser_vec(&proof)?;
	header_bytes.append(&mut proof_bytes);
	println!("proof: {:?}", proof_bytes);
	println!("header bytes: {:?}", header_bytes);

	let header: BlockHeader = ser::deserialize(&mut header_bytes.as_slice())?;
	Ok(header)
}
```
Closing this issue.

**Closed by quentinlesceller** 2019-04-01 14:54 UTC
